### ISSUE TITLE
cannot resolve './extend' when using on esm

### ISSUE THREAD

**Issue by quino0627** [inhibitor1217/extended-enum#172]
**Describe the bug**

cannot find path of `./extend.js` file when using this library

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/33861398/161684594-f96e36e4-d9b4-4953-97bb-cf6e152a1bf8.png">

**To Reproduce**
1. install library on esm-based application (to access `/dist/mjs/index.js`)
2. import extend by `import {}` as written in [docs](https://inhibitor1217.github.io/extended-enum/docs/get-started/#tldr)
3. run webpack-dev server

**Expected behavior**
No Error should be existed

**Desktop (please complete the following information):**
extended-enum@1.0.0

**Additional context**

**Comment by inhibitor1217** [comment]
related to https://github.com/microsoft/TypeScript/issues/40878
